# Generated by Django 4.2.7 on 2025-12-12 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_degree', models.CharField(blank=True, help_text='Degree level (e.g., BSc, MSc, PhD). Controlled vocabulary - to be implemented.', max_length=100, null=True)),
                ('academic_rank', models.CharField(blank=True, help_text='Academic rank or year of study. Controlled vocabulary - to be implemented.', max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, help_text='Field of study/specialization. Controlled vocabulary - to be implemented.', max_length=100, null=True)),
                ('institution', models.CharField(blank=True, help_text='University or institution name.', max_length=255)),
                ('academic_year', models.CharField(blank=True, help_text='Academic year (e.g., 2024, 2025). Controlled vocabulary - to be implemented.', max_length=20, null=True)),
                ('research_experience', models.BooleanField(blank=True, help_text='Whether student has research experience. Nullable to allow unanswered state.', null=True)),
                ('research_experience_details', models.TextField(blank=True, help_text='Details about research experience.')),
                ('work_location_preference', models.CharField(blank=True, help_text='Preferred work location. Flexible format for now.', max_length=255)),
                ('availability_notes', models.TextField(blank=True, help_text='Availability information and constraints.')),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional notes or comments.')),
                ('start_date', models.DateField(blank=True, help_text='Preferred or available start date.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'db_table': 'student_profiles',
            },
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_rank', models.CharField(blank=True, help_text='Academic rank or position (e.g., Professor, Lecturer). Controlled vocabulary - to be implemented.', max_length=100, null=True)),
                ('department', models.CharField(blank=True, help_text='Department or faculty name.', max_length=255)),
                ('research_domains', models.JSONField(blank=True, default=list, help_text='List of research domains/areas. Stored as JSON array. Controlled vocabulary - to be implemented.')),
                ('research_description', models.TextField(blank=True, help_text='Description of research area and project.')),
                ('requirements', models.TextField(blank=True, help_text='Requirements and qualifications needed from students.')),
                ('constraints', models.TextField(blank=True, help_text='Constraints, limitations, or special conditions.')),
                ('reward_type', models.CharField(blank=True, help_text='Type of reward or compensation offered (e.g., credit, financial). Controlled vocabulary - to be implemented.', max_length=100, null=True)),
                ('work_type', models.CharField(blank=True, help_text='Work type (e.g., on-site, remote, hybrid). Controlled vocabulary - to be implemented.', max_length=100, null=True)),
                ('work_location', models.CharField(blank=True, help_text='Work location details.', max_length=255)),
                ('needed_students_count', models.PositiveIntegerField(blank=True, help_text='Number of students needed for the project.', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Project or opportunity start date.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor Profile',
                'verbose_name_plural': 'Mentor Profiles',
                'db_table': 'mentor_profiles',
            },
        ),
    ]
