# Generated by Django 5.2.8 on 2025-12-20 14:15

import apps.profiles.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_he', models.CharField(blank=True, help_text='Hebrew name for display', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Academic Rank',
                'verbose_name_plural': 'Academic Ranks',
                'db_table': 'ref_academic_ranks',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompensationPreference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_he', models.CharField(blank=True, help_text='Hebrew name for display', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compensation Preference',
                'verbose_name_plural': 'Compensation Preferences',
                'db_table': 'ref_compensation_preferences',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_he', models.CharField(blank=True, help_text='Hebrew name for display', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Degree',
                'verbose_name_plural': 'Degrees',
                'db_table': 'ref_degrees',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_he', models.CharField(blank=True, help_text='Hebrew name for display', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'db_table': 'ref_institutions',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalTrainingStage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_he', models.CharField(blank=True, help_text='Hebrew name for display', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Medical Training Stage',
                'verbose_name_plural': 'Medical Training Stages',
                'db_table': 'ref_medical_training_stages',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipationMode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_he', models.CharField(blank=True, help_text='Hebrew name for display', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Participation Mode',
                'verbose_name_plural': 'Participation Modes',
                'db_table': 'ref_participation_modes',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_he', models.CharField(blank=True, help_text='Hebrew name for display', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Professional Experience Level',
                'verbose_name_plural': 'Professional Experience Levels',
                'db_table': 'ref_professional_experience',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchInterest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_he', models.CharField(blank=True, help_text='Hebrew name for display', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Research Interest',
                'verbose_name_plural': 'Research Interests',
                'db_table': 'ref_research_interests',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_he', models.CharField(blank=True, help_text='Hebrew name for display', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
                'db_table': 'ref_specialties',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_he', models.CharField(blank=True, help_text='Hebrew name for display', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Work Type',
                'verbose_name_plural': 'Work Types',
                'db_table': 'ref_work_types',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='academic_degree',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='availability_notes',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='research_experience',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='work_location_preference',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='available_start_date',
            field=models.DateField(blank=True, help_text='Date when student can start', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='background_description',
            field=models.TextField(blank=True, help_text='Personal and academic background description'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='has_research_experience',
            field=models.BooleanField(default=False, help_text='Whether student has prior research experience'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_available_for_research',
            field=models.BooleanField(default=True, help_text='Whether student is currently available for research opportunities'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='study_start_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year when studies began (e.g., 2020)', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='study_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Current year of study (1-10). FE displays as א/ב/ג/ד...', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='weekly_hours_commitment',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of hours per week available (1-60)', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='workplace',
            field=models.CharField(blank=True, help_text='Current workplace (free text)', max_length=255),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='constraints',
            field=models.TextField(blank=True, help_text='Constraints, limitations, or special conditions'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='department',
            field=models.CharField(blank=True, help_text='Department or faculty name', max_length=255),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='needed_students_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of students needed', null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='requirements',
            field=models.TextField(blank=True, help_text='Requirements and qualifications needed from students'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='research_description',
            field=models.TextField(blank=True, help_text='Description of research area and project'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='research_domains',
            field=models.JSONField(blank=True, default=list, help_text='List of research domains/areas (JSON array)'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='start_date',
            field=models.DateField(blank=True, help_text='Project start date', null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='work_location',
            field=models.CharField(blank=True, help_text='Work location details', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='research_experience_details',
            field=models.TextField(blank=True, help_text='Details about research experience. Required if has_research_experience=True'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='academic_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_profiles', to='profiles.academicrank'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='academic_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='profiles.academicrank'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='compensation_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='profiles.compensationpreference'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='reward_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_profiles', to='profiles.compensationpreference'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='degrees',
            field=models.ManyToManyField(blank=True, related_name='student_profiles', to='profiles.degree'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='profiles.institution'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='medical_training_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='profiles.medicaltrainingstage'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='participation_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_profiles', to='profiles.participationmode'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='participation_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='profiles.participationmode'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='professional_experience_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='profiles.professionalexperience'),
        ),
        migrations.CreateModel(
            name='ProfessionalRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommender_name', models.CharField(max_length=255)),
                ('recommender_email', models.EmailField(max_length=254)),
                ('recommender_title', models.CharField(blank=True, help_text='Professional title or position', max_length=255)),
                ('recommender_institution', models.CharField(blank=True, help_text='Institution or organization', max_length=255)),
                ('relationship', models.CharField(blank=True, help_text="Relationship to student (e.g., 'Research Supervisor')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='profiles.studentprofile')),
            ],
            options={
                'verbose_name': 'Professional Recommendation',
                'verbose_name_plural': 'Professional Recommendations',
                'db_table': 'professional_recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.profiles.models.profile_document_upload_path)),
                ('document_type', models.CharField(choices=[('CV', 'Curriculum Vitae'), ('TRANSCRIPT', 'Academic Transcript'), ('CERTIFICATE', 'Certificate'), ('RECOMMENDATION', 'Recommendation Letter'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.studentprofile')),
            ],
            options={
                'verbose_name': 'Profile Document',
                'verbose_name_plural': 'Profile Documents',
                'db_table': 'profile_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='research_interest_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='profiles.researchinterest'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='profiles.specialty'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='desired_work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='profiles.worktype'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_profiles', to='profiles.worktype'),
        ),
    ]
