# Generated by Django 4.2.7 on 2026-01-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_seed_frontend_reference_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='hasMentoringExperience',
            field=models.BooleanField(db_column='has_mentoring_experience', default=False, help_text='Whether mentor has prior mentoring experience'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='mentoringExperienceDetails',
            field=models.TextField(blank=True, db_column='mentoring_experience_details', help_text='Details about mentoring experience'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='personalAcademicDescription',
            field=models.TextField(blank=True, db_column='personal_academic_description', help_text='Personal and academic background description'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='previousResearchDescription',
            field=models.TextField(blank=True, db_column='previous_research_description', help_text='Description of previous research'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='recommendationRequest',
            field=models.TextField(blank=True, db_column='recommendation_request', help_text='Request for recommendations (name + email)'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='researchInterests',
            field=models.ForeignKey(blank=True, db_column='research_interests_id', help_text='Research interest area', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentor_profiles', to='profiles.researchinterest'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='hasResearchExperience',
            field=models.BooleanField(db_column='has_research_experience', default=False, help_text='Whether student has prior research experience'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='isAvailableForResearch',
            field=models.BooleanField(db_column='is_available_for_research', default=True, help_text='Whether student is currently available for research'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='isShebaEmployee',
            field=models.BooleanField(db_column='is_sheba_employee', default=False, help_text='Whether student is employed at Sheba'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='personalAcademicDescription',
            field=models.TextField(blank=True, db_column='personal_academic_description', help_text='Personal and academic background description'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='professionalExperience',
            field=models.TextField(blank=True, db_column='professional_experience', help_text='Previous professional experience'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='recommendationRequest',
            field=models.TextField(blank=True, db_column='recommendation_request', help_text='Request for recommendations (name + email)'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='researchExperienceDetails',
            field=models.TextField(blank=True, db_column='research_experience_details', help_text='Details about research experience'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='softwareSkills',
            field=models.TextField(blank=True, db_column='software_skills', help_text='Software skills and tools (SPSS, Python, etc.)'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='startDate',
            field=models.DateField(blank=True, db_column='start_date', help_text='Date when student can start', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='startYear',
            field=models.PositiveIntegerField(blank=True, db_column='start_year', help_text='Year when studies began (e.g., 2020)', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='weeklyHours',
            field=models.PositiveSmallIntegerField(blank=True, db_column='weekly_hours', help_text='Number of hours per week available', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='yearOfStudy',
            field=models.CharField(blank=True, db_column='year_of_study', help_text='Current year of study displayed as א/ב/ג/ד...', max_length=10),
        ),
    ]
