# Generated by Django 4.2.7 on 2026-01-11 19:44

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_update_reference_english_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to=apps.profiles.models.mentor_avatar_path),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to=apps.profiles.models.student_avatar_path),
        ),
    ]
