# Generated by Django 4.2.7 on 2026-02-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_recommenders_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='compensationPreference',
            field=models.JSONField(blank=True, default=list, help_text='Compensation preferences, e.g. ["מלגה", "שכר"]'),
        ),
    ]
