# Generated by Django 4.2.7 on 2026-03-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_change_compensationPreference_to_jsonfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='linkedinUrl',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='recommenders',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='specialties',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='compensationPreference',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='linkedinUrl',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='recommenders',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='specialties',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='recommendationRequest',
            field=models.TextField(blank=True, db_column='recommendation_request', help_text='Request for recommendations (name + email)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='recommendationRequest',
            field=models.TextField(blank=True, db_column='recommendation_request', help_text='Request for recommendations (name + email)'),
        ),
    ]
