# Generated by Django 4.2.7 on 2026-05-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_add_bsc_degree_and_fix_training_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='specialty_other',
            field=models.CharField(blank=True, db_column='specialty_other', help_text="Free-text specialization when 'Other' is selected", max_length=255),
        ),
    ]
