# Generated by Django 4.2.7 on 2026-02-24 16:10

from django.db import migrations, models


def convert_gender_values(apps, schema_editor):
    """Convert existing 'man'→'male' and 'woman'→'female' values."""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(gender='man').update(gender='male')
    User.objects.filter(gender='woman').update(gender='female')


def revert_gender_values(apps, schema_editor):
    """Revert 'male'→'man' and 'female'→'woman' values."""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(gender='male').update(gender='man')
    User.objects.filter(gender='female').update(gender='woman')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_email_verified'),
    ]

    operations = [
        migrations.RunPython(
            convert_gender_values,
            revert_gender_values,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'זכר'), ('female', 'נקבה'), ('other', 'אחר')], max_length=10, null=True),
        ),
    ]
