# Generated by Django 4.2.7 on 2026-03-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_fix_gender_choices'),
        ('accounts', '0008_gender_male_female_choices'),
    ]

    operations = [
    ]
