# Generated by Django 4.2.7 on 2026-05-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_gender_to_male_female'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
