# Generated by Django 4.2.7 on 2026-02-19 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0003_research_form_improvements'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchapplication',
            name='mentor_note',
            field=models.TextField(blank=True, help_text='Optional note from mentor on application decision'),
        ),
        migrations.AlterField(
            model_name='research',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('completed', 'Completed')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='research',
            name='teamSize',
            field=models.PositiveIntegerField(blank=True, help_text='Total team size', null=True),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='research.research')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
