# Generated by Django 4.2.7 on 2026-02-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_contactmessage_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='notification_type',
            field=models.CharField(choices=[('contact', 'Contact Message'), ('application_new', 'New Application'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('application_invited', 'Research Invitation')], default='contact', max_length=30),
        ),
        migrations.AlterField(
            model_name='researchapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('invited', 'Invited')], default='pending', max_length=20),
        ),
    ]
