# Generated by Django 4.2.7 on 2026-02-24 16:04

import json
from django.db import migrations, models


def convert_compensation_strings_to_json(apps, schema_editor):
    """Convert existing string compensation values to JSON list strings
    so they pass SQLite's JSON_VALID check when the column type changes."""
    Research = apps.get_model('research', 'Research')
    for research in Research.objects.all():
        old_val = research.compensation
        if isinstance(old_val, str) and old_val.strip():
            # Convert "מלגה" → '["מלגה"]'
            research.compensation = json.dumps([old_val.strip()], ensure_ascii=False)
        else:
            research.compensation = '[]'
        research.save(update_fields=['compensation'])


def revert_compensation_to_string(apps, schema_editor):
    """Revert JSON list compensation values back to strings."""
    Research = apps.get_model('research', 'Research')
    for research in Research.objects.all():
        val = research.compensation
        if isinstance(val, list) and val:
            research.compensation = val[0]
        elif isinstance(val, str):
            try:
                parsed = json.loads(val)
                research.compensation = parsed[0] if parsed else ''
            except (json.JSONDecodeError, IndexError):
                research.compensation = val
        else:
            research.compensation = ''
        research.save(update_fields=['compensation'])


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_add_removed_status_and_notification'),
    ]

    operations = [
        # Step 1: Convert existing string data to JSON-valid strings
        migrations.RunPython(
            convert_compensation_strings_to_json,
            revert_compensation_to_string,
        ),
        # Step 2: Change column type from CharField to JSONField
        migrations.AlterField(
            model_name='research',
            name='compensation',
            field=models.JSONField(blank=True, default=list, help_text='Primary compensation types, e.g. ["מלגה", "שכר"]'),
        ),
    ]
