# Generated by Django 4.2.7 on 2026-02-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0015_remove_team_researchers_and_interns_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchapplication',
            name='can_approve',
            field=models.BooleanField(default=False, help_text='Can approve/reject applicants'),
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='can_edit',
            field=models.BooleanField(default=False, help_text='Can edit research details'),
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='can_invite',
            field=models.BooleanField(default=False, help_text='Can invite users to the research'),
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='can_remove',
            field=models.BooleanField(default=False, help_text='Can remove approved members'),
        ),
    ]
