# Generated by Django 4.2.7 on 2026-02-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0017_researchapplication_can_manage_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='owner_last_seen_chat_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='last_seen_chat_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='notification_type',
            field=models.CharField(choices=[('contact', 'Contact Message'), ('application_new', 'New Application'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('application_invited', 'Research Invitation'), ('application_removed', 'Removed from Research'), ('chat_mention', 'Chat Mention')], default='contact', max_length=30),
        ),
    ]
