# Generated by Django 4.2.7 on 2026-03-04 20:11

import apps.research.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0019_remove_researchchatmessage_pinned_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='durationWeeks',
        ),
        migrations.AddField(
            model_name='research',
            name='accepting_applications',
            field=models.BooleanField(default=True, help_text='Whether this research is currently accepting new applications'),
        ),
        migrations.AddField(
            model_name='research',
            name='durationMonths',
            field=models.PositiveIntegerField(blank=True, db_column='duration_months', null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='estimatedCompletionDate',
            field=models.DateField(blank=True, db_column='estimated_completion_date', help_text='Estimated project completion date', null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='research',
            name='moderation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='research',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Review'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='research',
            name='owner_last_seen_chat_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='can_approve',
            field=models.BooleanField(default=False, help_text='Can approve/reject applicants'),
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='can_edit',
            field=models.BooleanField(default=False, help_text='Can edit research details'),
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='can_invite',
            field=models.BooleanField(default=False, help_text='Can invite users to the research'),
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='can_manage_chat',
            field=models.BooleanField(default=False, help_text='Can manage chat settings and pin messages'),
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='can_remove',
            field=models.BooleanField(default=False, help_text='Can remove approved members'),
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='last_seen_chat_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='mentor_note',
            field=models.TextField(blank=True, help_text='Optional note from mentor on application decision'),
        ),
        migrations.AlterField(
            model_name='research',
            name='compensation',
            field=models.JSONField(blank=True, default=list, help_text='Primary compensation types, e.g. ["מלגה", "שכר"]'),
        ),
        migrations.AlterField(
            model_name='research',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('completed', 'Completed')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='research',
            name='teamSize',
            field=models.PositiveIntegerField(blank=True, help_text='Total team size', null=True),
        ),
        migrations.AlterField(
            model_name='researchapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('invited', 'Invited'), ('removed', 'Removed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ResearchChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_permission', models.CharField(choices=[('all', 'All Members'), ('mentors_only', 'Mentors Only')], default='all', max_length=20)),
                ('files_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to='research.research')),
            ],
            options={
                'db_table': 'research_chat_settings',
            },
        ),
        migrations.CreateModel(
            name='ResearchChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=2000)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.research.models.research_chat_upload_path)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pinned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='research.research')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'research_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('contact', 'Contact Message'), ('application_new', 'New Application'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('application_invited', 'Research Invitation'), ('application_removed', 'Removed from Research'), ('chat_mention', 'Chat Mention')], default='contact', max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=2000)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='research.research')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
