# Generated by Django 4.2.7 on 2026-03-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0022_research_academic_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='research',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Review'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='research',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('completed', 'Completed')], db_index=True, default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='researchapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('invited', 'Invited'), ('removed', 'Removed')], db_index=True, default='pending', max_length=20),
        ),
    ]
