# Generated by Django 5.2.8 on 2025-12-20 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_seed_reference_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='constraints',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='needed_students_count',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='participation_mode',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='research_description',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='research_domains',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='reward_type',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='work_location',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='work_type',
        ),
        migrations.RemoveField(
            model_name='professionalrecommendation',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profiledocument',
            name='profile',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='background_description',
            field=models.TextField(blank=True, help_text='Personal and academic background description (תיאור רקע אישי ואקדמי)'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='degrees',
            field=models.ManyToManyField(blank=True, related_name='mentor_profiles', to='profiles.degree'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='has_mentoring_experience',
            field=models.BooleanField(default=False, help_text='Whether mentor has prior mentoring experience'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentor_profiles', to='profiles.institution'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='medical_training_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentor_profiles', to='profiles.medicaltrainingstage'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='mentoring_experience_details',
            field=models.TextField(blank=True, help_text='Details about mentoring experience. Required if has_mentoring_experience=True'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='previous_research_description',
            field=models.TextField(blank=True, help_text='Description of previous research (תיאור מחקרים קודמים)'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='research_interest_field',
            field=models.ForeignKey(blank=True, help_text='Research interest area', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentor_profiles', to='profiles.researchinterest'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentor_profiles', to='profiles.specialty'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='workplace',
            field=models.CharField(blank=True, help_text='Current workplace', max_length=255),
        ),
        migrations.AddField(
            model_name='professionalrecommendation',
            name='mentor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='profiles.mentorprofile'),
        ),
        migrations.AddField(
            model_name='professionalrecommendation',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='profiles.studentprofile'),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='mentor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.mentorprofile'),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.studentprofile'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='academic_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentor_profiles', to='profiles.academicrank'),
        ),
        migrations.AlterField(
            model_name='professionalrecommendation',
            name='relationship',
            field=models.CharField(blank=True, help_text="Relationship to the profile owner (e.g., 'Research Supervisor')", max_length=255),
        ),
        migrations.AddConstraint(
            model_name='professionalrecommendation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('mentor_profile__isnull', True), ('student_profile__isnull', False)), models.Q(('mentor_profile__isnull', False), ('student_profile__isnull', True)), _connector='OR'), name='recommendation_exactly_one_profile'),
        ),
        migrations.AddConstraint(
            model_name='profiledocument',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('mentor_profile__isnull', True), ('student_profile__isnull', False)), models.Q(('mentor_profile__isnull', False), ('student_profile__isnull', True)), _connector='OR'), name='document_exactly_one_profile'),
        ),
    ]
