# Generated by Django 4.2.7 on 2025-12-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_mentor_profile_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledocument',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename before UUID prefix was added', max_length=255),
        ),
    ]
