# Generated by Django 4.2.7 on 2026-03-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_remove_mentorprofile_linkedinurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='recommendationRequest',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='recommendationRequest',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='linkedinUrl',
            field=models.URLField(blank=True, db_column='linkedin_url', help_text='LinkedIn profile URL', max_length=500),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='recommenders',
            field=models.JSONField(blank=True, db_column='recommenders', default=list, help_text='List of recommenders [{name, email, phone}, ...]'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='specialties',
            field=models.ManyToManyField(blank=True, help_text='Multiple specialties (replaces single specialty FK)', related_name='mentor_profiles_multi', to='profiles.specialty'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='compensationPreference',
            field=models.JSONField(blank=True, default=list, help_text='Compensation preferences, e.g. ["מלגה", "שכר"]'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedinUrl',
            field=models.URLField(blank=True, db_column='linkedin_url', help_text='LinkedIn profile URL', max_length=500),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='recommenders',
            field=models.JSONField(blank=True, db_column='recommenders', default=list, help_text='List of recommenders [{name, email, phone}, ...]'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='specialties',
            field=models.ManyToManyField(blank=True, help_text='Multiple specialties (replaces single specialty FK)', related_name='student_profiles_multi', to='profiles.specialty'),
        ),
    ]
