# Generated by Django 4.2.7 on 2026-02-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_copy_specialty_fk_to_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='linkedinUrl',
            field=models.URLField(blank=True, db_column='linkedin_url', help_text='LinkedIn profile URL', max_length=500),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedinUrl',
            field=models.URLField(blank=True, db_column='linkedin_url', help_text='LinkedIn profile URL', max_length=500),
        ),
    ]
