# Generated by Django 4.2.7 on 2026-02-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_remove_hit_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='recommendationRequest',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='recommendationRequest',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='recommenderEmail',
            field=models.EmailField(blank=True, db_column='recommender_email', help_text='Recommender email address', max_length=254),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='recommenderName',
            field=models.CharField(blank=True, db_column='recommender_name', help_text='Recommender full name', max_length=255),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='recommenderPhone',
            field=models.CharField(blank=True, db_column='recommender_phone', help_text='Recommender phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='recommenderEmail',
            field=models.EmailField(blank=True, db_column='recommender_email', help_text='Recommender email address', max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='recommenderName',
            field=models.CharField(blank=True, db_column='recommender_name', help_text='Recommender full name', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='recommenderPhone',
            field=models.CharField(blank=True, db_column='recommender_phone', help_text='Recommender phone number', max_length=20),
        ),
    ]
