# Generated by Django 4.2.7 on 2026-02-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_split_recommendation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='recommenderEmail',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='recommenderName',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='recommenderPhone',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='recommenderEmail',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='recommenderName',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='recommenderPhone',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='recommenders',
            field=models.JSONField(blank=True, db_column='recommenders', default=list, help_text='List of recommenders [{name, email, phone}, ...]'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='recommenders',
            field=models.JSONField(blank=True, db_column='recommenders', default=list, help_text='List of recommenders [{name, email, phone}, ...]'),
        ),
    ]
