# Generated by Django 4.2.7 on 2026-03-21 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_convert_fk_to_text_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mentor Profile', 'verbose_name_plural': 'Mentor Profiles'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AlterField(
            model_name='academicrank',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='compensationpreference',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='medicaltrainingstage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='participationmode',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='researchinterest',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='specialtygroup',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='apprenticeStage',
            field=models.ForeignKey(blank=True, db_column='apprentice_stage_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='profiles.medicaltrainingstage'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='profiles.institution'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='participationMode',
            field=models.ForeignKey(blank=True, db_column='participation_mode_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='profiles.participationmode'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='profiles.specialty'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='specialtyGroup',
            field=models.ForeignKey(blank=True, db_column='specialty_group_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='profiles.specialtygroup'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
