# Generated by Django 4.2.7 on 2026-02-21 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('research_approve', 'Research Approved'), ('research_reject', 'Research Rejected'), ('research_flag', 'Research Flagged'), ('research_soft_delete', 'Research Soft-Deleted'), ('research_restore', 'Research Restored'), ('user_deactivate', 'User Deactivated'), ('user_reactivate', 'User Reactivated'), ('user_force_verify', 'User Force-Verified')], max_length=30)),
                ('target_research_id', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_action_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
