# Generated by Django 4.2.7 on 2026-02-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_sitesetting_require_email_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='require_email_verification_to_apply',
            field=models.BooleanField(default=False),
        ),
    ]
