# Generated by Django 4.2.7 on 2026-03-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_sitesetting_mentor_registration_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemannouncement',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
