# Generated by Django 4.2.7 on 2026-05-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_add_announcement_is_active_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='action_type',
            field=models.CharField(choices=[('research_approve', 'Research Approved'), ('research_reject', 'Research Rejected'), ('research_flag', 'Research Flagged'), ('research_soft_delete', 'Research Soft-Deleted'), ('research_restore', 'Research Restored'), ('user_deactivate', 'User Deactivated'), ('user_reactivate', 'User Reactivated'), ('user_force_verify', 'User Force-Verified'), ('research_edit', 'Research Edited'), ('settings_updated', 'Settings Updated'), ('announcement_create', 'Announcement Created'), ('announcement_update', 'Announcement Updated'), ('announcement_deactivate', 'Announcement Deactivated'), ('user_edit', 'User Edited'), ('application_override', 'Application Status Overridden'), ('user_delete', 'User Deleted'), ('profile_delete', 'Profile Deleted')], max_length=40),
        ),
    ]
