from django.urls import path

from .views import (
    researches,
    research_detail,
    my_researches,
    my_research_detail,
    invite_to_research,
    accept_invite,
    decline_invite,
    apply_to_research,
    cancel_my_application,
    leave_research,
    my_research_applications,
    approve_application,
    reject_application,
    remove_application,
    update_mentor_permissions,
    my_application_status,
    research_approved_applicants,
    my_joined_researches,
    my_applications_dashboard,
    contact_research_owner,
    contact_user,
    secure_contract_download,
    inbox,
    unread_count,
    mark_read,
    mark_all_read,
    research_chat,
    research_chat_settings,
    research_chat_pin,
    research_chat_delete,
    research_chat_mark_seen,
    research_chat_members,
)

urlpatterns = [
    path("", researches, name="researches"),
    path("joined/", my_joined_researches, name="my-joined-researches"),
    path("my-applications/", my_applications_dashboard, name="my-applications-dashboard"),
    path("<int:research_id>/", research_detail, name="research-detail"),
    path("<int:research_id>/contact/", contact_research_owner, name="research-contact-owner"),
    path("<int:research_id>/contract/", secure_contract_download, name="research-contract-download"),
    path(
        "<int:research_id>/approved-applicants/",
        research_approved_applicants,
        name="research-approved-applicants",
    ),
    path("<int:research_id>/apply/", apply_to_research, name="research-apply"),
    path("<int:research_id>/cancel/", cancel_my_application, name="research-cancel"),
    path("<int:research_id>/leave/", leave_research, name="research-leave"),
    path("<int:research_id>/my-application/", my_application_status, name="research-my-application"),
    path("<int:research_id>/accept-invite/", accept_invite, name="research-accept-invite"),
    path("<int:research_id>/decline-invite/", decline_invite, name="research-decline-invite"),
    path("me/", my_researches, name="my-researches"),
    path("me/<int:research_id>/", my_research_detail, name="my-research-detail"),
    path("me/<int:research_id>/invite/", invite_to_research, name="research-invite"),
    path("me/<int:research_id>/applications/", my_research_applications, name="my-research-applications"),
    path(
        "me/<int:research_id>/applications/<int:application_id>/approve/",
        approve_application,
        name="research-application-approve",
    ),
    path(
        "me/<int:research_id>/applications/<int:application_id>/reject/",
        reject_application,
        name="research-application-reject",
    ),
    path(
        "me/<int:research_id>/applications/<int:application_id>/remove/",
        remove_application,
        name="research-application-remove",
    ),
    path(
        "me/<int:research_id>/applications/<int:application_id>/permissions/",
        update_mentor_permissions,
        name="research-application-permissions",
    ),
    path("me/<int:research_id>/chat/", research_chat, name="research-chat"),
    path("me/<int:research_id>/chat/settings/", research_chat_settings, name="research-chat-settings"),
    path("me/<int:research_id>/chat/<int:message_id>/pin/", research_chat_pin, name="research-chat-pin"),
    path("me/<int:research_id>/chat/seen/", research_chat_mark_seen, name="research-chat-mark-seen"),
    path("me/<int:research_id>/chat/members/", research_chat_members, name="research-chat-members"),
    path("me/<int:research_id>/chat/<int:message_id>/", research_chat_delete, name="research-chat-delete"),
    path("messages/inbox/", inbox, name="messages-inbox"),
    path("messages/unread-count/", unread_count, name="messages-unread-count"),
    path("messages/<int:message_id>/read/", mark_read, name="messages-mark-read"),
    path("messages/mark-all-read/", mark_all_read, name="messages-mark-all-read"),
    path("messages/contact-user/", contact_user, name="messages-contact-user"),
]
