# Generated by Django 4.2.7 on 2026-05-19 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('research', 'Research'), ('mentor_profile', 'Mentor Profile'), ('student_profile', 'Student Profile')], max_length=20)),
                ('object_id', models.CharField(help_text='UUID (profiles) or integer ID (research) of the saved target.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='saveditem',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_saved_item_per_user'),
        ),
    ]
