# Generated by Django 4.2.7 on 2026-01-12 15:17

import apps.research.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('researchName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('researchArea', models.CharField(blank=True, max_length=255)),
                ('mentors', models.CharField(blank=True, max_length=255)),
                ('teamSize', models.PositiveIntegerField(blank=True, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('weeklyHours', models.PositiveIntegerField(blank=True, null=True)),
                ('durationWeeks', models.PositiveIntegerField(blank=True, null=True)),
                ('compensation', models.CharField(blank=True, max_length=100)),
                ('workMode', models.CharField(blank=True, max_length=50)),
                ('requirements', models.TextField(blank=True)),
                ('skillsAndTools', models.TextField(blank=True)),
                ('output', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('helsinkiApproval', models.CharField(blank=True, max_length=100)),
                ('dataType', models.CharField(blank=True, max_length=50)),
                ('contract', models.FileField(blank=True, null=True, upload_to=apps.research.models.research_contract_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'researches',
                'ordering': ['-created_at'],
            },
        ),
    ]
