# Generated by Django 4.2.7 on 2026-01-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchApplication",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="research.research",
                    ),
                ),
            ],
            options={
                "db_table": "research_applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="researchapplication",
            constraint=models.UniqueConstraint(
                fields=("research", "applicant"),
                name="uniq_research_applicant",
            ),
        ),
    ]
