# Generated by Django 4.2.7 on 2026-02-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_contactmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='notification_type',
            field=models.CharField(choices=[('contact', 'Contact Message'), ('application_new', 'New Application'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected')], default='contact', max_length=30),
        ),
    ]
