# Generated by Django 4.2.7 on 2026-02-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_alter_contactmessage_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='accepting_applications',
            field=models.BooleanField(default=True, help_text='Whether this research is currently accepting new applications'),
        ),
    ]
