# Generated by Django 4.2.7 on 2026-02-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_accepting_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
