# Generated by Django 4.2.7 on 2026-02-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_compensation_to_jsonfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='compensationTypes',
        ),
    ]
