# Generated by Django 4.2.7 on 2026-02-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0013_remove_compensation_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='durationWeeks',
            new_name='durationMonths',
        ),
        migrations.AlterField(
            model_name='research',
            name='durationMonths',
            field=models.PositiveIntegerField(blank=True, db_column='duration_months', null=True),
        ),
    ]
