# Generated by Django 4.2.7 on 2026-02-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_duration_weeks_to_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='teamInternsCount',
        ),
        migrations.RemoveField(
            model_name='research',
            name='teamResearchersCount',
        ),
    ]
