# Generated by Django 4.2.7 on 2026-02-25 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0016_researchapplication_can_approve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchapplication',
            name='can_manage_chat',
            field=models.BooleanField(default=False, help_text='Can manage chat settings and pin messages'),
        ),
        migrations.CreateModel(
            name='ResearchChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_permission', models.CharField(choices=[('all', 'All Members'), ('mentors_only', 'Mentors Only')], default='all', max_length=20)),
                ('files_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to='research.research')),
            ],
            options={
                'db_table': 'research_chat_settings',
            },
        ),
        migrations.CreateModel(
            name='ResearchChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=2000)),
                ('file', models.FileField(blank=True, null=True, upload_to='research_chat_files/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pinned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='research.research')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'research_chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
