# Generated by Django 4.2.7 on 2026-03-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0018_research_owner_last_seen_chat_message_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchchatmessage',
            name='pinned_by',
        ),
        migrations.RemoveField(
            model_name='researchchatmessage',
            name='research',
        ),
        migrations.RemoveField(
            model_name='researchchatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='researchchatsettings',
            name='research',
        ),
        migrations.RemoveField(
            model_name='research',
            name='accepting_applications',
        ),
        migrations.RemoveField(
            model_name='research',
            name='durationMonths',
        ),
        migrations.RemoveField(
            model_name='research',
            name='estimatedCompletionDate',
        ),
        migrations.RemoveField(
            model_name='research',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='research',
            name='moderation_note',
        ),
        migrations.RemoveField(
            model_name='research',
            name='moderation_status',
        ),
        migrations.RemoveField(
            model_name='research',
            name='owner_last_seen_chat_message_id',
        ),
        migrations.RemoveField(
            model_name='researchapplication',
            name='can_approve',
        ),
        migrations.RemoveField(
            model_name='researchapplication',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='researchapplication',
            name='can_invite',
        ),
        migrations.RemoveField(
            model_name='researchapplication',
            name='can_manage_chat',
        ),
        migrations.RemoveField(
            model_name='researchapplication',
            name='can_remove',
        ),
        migrations.RemoveField(
            model_name='researchapplication',
            name='last_seen_chat_message_id',
        ),
        migrations.RemoveField(
            model_name='researchapplication',
            name='mentor_note',
        ),
        migrations.AddField(
            model_name='research',
            name='durationWeeks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='compensation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='research',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='research',
            name='teamSize',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='ResearchChatMessage',
        ),
        migrations.DeleteModel(
            name='ResearchChatSettings',
        ),
    ]
