# Generated by Django 4.2.7 on 2026-04-13 10:33

import apps.research.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0023_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('needs_help', 'Needs Help'), ('completed', 'Completed')], db_index=True, default='todo', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'research_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_task_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='research.researchtask')),
            ],
            options={
                'db_table': 'research_task_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.research.models.research_task_attachment_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='research.researchtask')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_task_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'research_task_attachments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTaskAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', help_text="Free-form display role (e.g. 'manager', 'student', 'owner').", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignees', to='research.researchtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_task_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'research_task_assignees',
            },
        ),
        migrations.AddField(
            model_name='researchtask',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_research_tasks', through='research.ResearchTaskAssignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchtask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_research_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchtask',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='research.research'),
        ),
        migrations.AddConstraint(
            model_name='researchtaskassignee',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='uniq_task_user'),
        ),
        migrations.AddIndex(
            model_name='researchtask',
            index=models.Index(fields=['research', 'status'], name='research_ta_researc_cb97d3_idx'),
        ),
        migrations.AddIndex(
            model_name='researchtask',
            index=models.Index(fields=['research', 'urgency'], name='research_ta_researc_829131_idx'),
        ),
    ]
