# Generated by Django 4.2.7 on 2026-02-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_applications_per_student', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('max_applications_per_research', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('default_moderation_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='approved', max_length=10)),
                ('contact_message_max_length', models.PositiveIntegerField(default=2000)),
                ('mentor_note_max_length', models.PositiveIntegerField(default=1000)),
                ('applications_globally_enabled', models.BooleanField(default=True)),
                ('registration_enabled', models.BooleanField(default=True)),
                ('require_email_verification_to_apply', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'site_settings',
            },
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='action_type',
            field=models.CharField(choices=[('research_approve', 'Research Approved'), ('research_reject', 'Research Rejected'), ('research_flag', 'Research Flagged'), ('research_soft_delete', 'Research Soft-Deleted'), ('research_restore', 'Research Restored'), ('user_deactivate', 'User Deactivated'), ('user_reactivate', 'User Reactivated'), ('user_force_verify', 'User Force-Verified'), ('settings_updated', 'Settings Updated')], max_length=30),
        ),
    ]
