# Generated by Django 4.2.7 on 2026-03-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_change_require_email_verification_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='mentor_registration_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='student_registration_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
